### PR TITLE
Ssss

### PR DESCRIPTION
**Pull request by S5SS**
Just miscellaneous tweaks

### CODE REVIEW

**Comment by Novaras** [comment]
salvettes not having kam was intentional or no?

**Comment by S5SS** [comment]
Not sure, I dont see a reason they cant have kamikaze though

**Comment by Novaras** [comment]
maybe so you cant suddenly kam them vs a ship they were towing or something

**Comment by S5SS** [comment]
hmm perhaps, the damage seems to be pretty low though, the multiplier is the same as for colls which reduces the damage a fair bit I believe

**Comment by S5SS** [comment]
if it becomes op somehow then the damage mult can be reduced so theyll still be able to kamikaze like you would logically think they should be able to but deal amounts of damage that arent worth it

**Pull request merged**
